import Head from "next/head";
import useSWR from "swr";
import type { InferRequestType } from "hono/client";
import { client } from "@/client";

export default function Home() {
  const $get = client.api.hello.$get;
  const fetcher = (arg: InferRequestType<typeof $get>) => async () => {
    const res = await $get(arg);
    if (res.ok) {
      return await res.json();
    }
  };

  const { data, error, isLoading } = useSWR(
    "/api/hello",
    fetcher({ query: { name: "hello" } }),
  );

  return (
    <>
      <Head>
        <title>Nextjs and Hono RPC example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{isLoading ? "...loading" : data}</div>
      <div>{error ? error.toString() : null}</div>
    </>
  );
}
